Reader
maiste/eos pull request #14
Opened 2019-06-23 10:19 UTC by maiste

* Add a reader module in core library. Fixes #9.
* Add reader.ml tests with OUnit. It will be moved to alcotest in another branch.

2019-06-23 21:01 UTC, xavitator requested changes

2019-06-24 06:11 UTC, maiste commented on src/core/reader.ml
> +let read_file file : string list option =
Using option type is more functional : but both are OCaml style : that's the power of OCaml ;)

2019-06-24 08:34 UTC, xavitator commented on src/core/reader.ml
> +let read_file file : string list option =
okok, all right.

2019-06-24 08:57 UTC, maiste commented on src/core/reader.ml
> +let read_file file : string list option =
You can validate the PR if it's ok for you :wink:

2019-06-24 10:11 UTC, xavitator approved these changes

2019-06-24 10:40 UTC, merged